# Generated by Django 5.1.1 on 2024-10-03 05:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefjh12345', length=22, max_length=25, prefix='cat', unique=True),
        ),
    ]
