# Generated by Django 5.1.1 on 2024-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_review', max_length=100),
        ),
    ]
