# Generated by Django 5.1.1 on 2024-10-07 11:25

import ecommapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_vendor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor/default.png', upload_to=ecommapp.models.user_directory_path),
        ),
    ]
