# Generated by Django 5.1.1 on 2024-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0015_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.CharField(choices=[('1', '⭐☆☆☆☆'), ('2', '⭐⭐☆☆☆'), ('3', '⭐⭐⭐☆☆'), ('4', '⭐⭐⭐⭐☆'), ('5', '⭐⭐⭐⭐⭐')], default=None, max_length=10),
        ),
    ]
