# Generated by Django 5.1.1 on 2024-10-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0016_alter_product_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ecommapp.product'),
        ),
    ]
