# Generated by Django 5.1.1 on 2024-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0017_alter_product_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Process', max_length=30),
        ),
    ]
