# Generated by Django 5.1.1 on 2024-10-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0018_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
