# Generated by Django 5.1.1 on 2024-10-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0019_address_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
