# Generated by Django 5.1.1 on 2024-10-23 10:51

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0023_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=22, max_length=10, prefix='oid', unique=True),
        ),
    ]
