# Generated by Django 5.1.1 on 2024-10-23 10:56

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0024_cartorder_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='product_sku',
            field=models.ManyToManyField(to='ecommapp.product'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='oid', unique=True),
        ),
    ]
