# Generated by Django 5.1.1 on 2024-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0027_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='ecommapp.coupon'),
        ),
    ]
