# Generated by Django 5.1.1 on 2024-10-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0028_cartorder_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='saved_price',
            new_name='saved',
        ),
    ]
