# Generated by Django 5.1.1 on 2024-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0030_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Awaiting payment', 'Awaiting payment'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=30, null=True),
        ),
    ]
