# Generated by Django 5.1.1 on 2024-10-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_Details')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Profile Details',
                'verbose_name_plural': 'Profile Details',
            },
        ),
    ]
