# Generated by Django 5.1.1 on 2024-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_profile_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_details',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile_details',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
